import { addGlobalReminder, checkAlarms } from './alarms.js';
import { appState, getActiveAccount, pushActivity, saveLocal, setActiveAccount } from './state.js';
import { addLoan, deleteLoan, filterLoans, loanSummary, markLoanPaid } from './loans.js';
import { dayKey, downloadJson, esc, fmtDate, fmtDateTime, readFileJson, toNum, uid } from './utils.js';

let currentRoute='dashboard'; let loanFilter='All'; let loanSearch='';

export function toast(message){const n=document.createElement('div');n.className='toast';n.textContent=message;document.getElementById('toastRoot').appendChild(n);setTimeout(()=>n.remove(),2500)}
window.addEventListener('toast',e=>toast(e.detail));

export function openModal({title,body,onSave,saveText='Save'}){const overlay=document.createElement('div');overlay.className='modal-overlay';overlay.innerHTML=`<div class="modal"><h3>${esc(title)}</h3><div>${body}</div><div class="inline" style="justify-content:flex-end;margin-top:.7rem"><button class="btn" data-cancel>Cancel</button><button class="btn primary" data-save>${saveText}</button></div></div>`;overlay.onclick=(e)=>{if(e.target===overlay||e.target.dataset.cancel!==undefined)overlay.remove();if(e.target.dataset.save!==undefined){onSave?.(overlay);}};document.getElementById('modalRoot').appendChild(overlay)}

export function render(){
  document.body.classList.toggle('dark',!!appState.settings.darkMode);
  renderAccountDropdown(); renderRoute(); renderAlarmBadge();
}

function renderRoute(){
  document.querySelectorAll('.view').forEach(v=>v.classList.remove('is-visible'));
  document.getElementById(`${currentRoute}View`).classList.add('is-visible');
  document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('is-active',b.dataset.route===currentRoute));
  if(currentRoute==='dashboard') renderDashboard();
  if(currentRoute==='accounts') renderAccounts();
  if(currentRoute==='loans') renderLoans();
  if(currentRoute==='activity') renderActivity();
  if(currentRoute==='settings') renderSettings();
}

function renderDashboard(){const acc=getActiveAccount(); if(!acc)return; const totalAcc=appState.accountOrder.length; const totalPoints=Object.values(appState.accountsData).reduce((a,x)=>a+toNum(x.points),0); const todayProgress=Math.round(((acc.pcDone/acc.targetPC)+(acc.mobDone/acc.targetMobile))*50); const activeLoans=Object.values(appState.accountsData).flatMap(a=>a.loans||[]).filter(l=>l.status==='Active').length;
  document.getElementById('activeAccountName').textContent=acc.name;
  document.getElementById('dashboardView').innerHTML=`<div class="grid"><article class="card"><h4>Total Accounts</h4><strong>${totalAcc}</strong></article><article class="card"><h4>Total Points</h4><strong>${totalPoints}</strong></article><article class="card"><h4>Today Progress</h4><strong>${todayProgress}%</strong></article><article class="card"><h4>Active Loans</h4><strong>${activeLoans}</strong></article></div>
  <div class="panel"><h3>${esc(acc.name)} Progress</h3><p>PC: ${acc.pcDone}/${acc.targetPC}</p><div class="progress"><div class="bar" style="width:${Math.min(100,Math.round(acc.pcDone/acc.targetPC*100))}%"></div></div><p>Mobile: ${acc.mobDone}/${acc.targetMobile}</p><div class="progress"><div class="bar" style="width:${Math.min(100,Math.round(acc.mobDone/acc.targetMobile*100))}%"></div></div><div class="inline" style="margin-top:.6rem"><button class="btn" id="addPcBtn">+PC</button><button class="btn" id="addMobBtn">+Mobile</button><button class="btn" id="addSessionBtn">Add Session</button></div></div>
  <div class="panel"><h3>Upcoming reminders</h3>${renderUpcoming()}</div>`;
  document.getElementById('addPcBtn').onclick=()=>{acc.pcDone++;acc.points++;pushActivity(`PC score incremented for ${acc.name}`);saveLocal();render()};
  document.getElementById('addMobBtn').onclick=()=>{acc.mobDone++;acc.points++;pushActivity(`Mobile score incremented for ${acc.name}`);saveLocal();render()};
  document.getElementById('addSessionBtn').onclick=()=>openModal({title:'Add Session',body:'<div class="form"><input name="title" placeholder="Session title"/></div>',onSave:(o)=>{const t=o.querySelector('[name=title]').value.trim();if(!t)return;acc.sessions.unshift({id:uid('ses'),title:t,time:new Date().toISOString()});pushActivity(`Session added: ${t}`);saveLocal();o.remove();render();}});
}
function renderUpcoming(){const rows=checkAlarms().slice(0,6).map(x=>`<tr><td>${esc(x.text||'Reminder')}</td><td>${esc(x.scope||'')}</td><td>${fmtDateTime(x.due)}</td></tr>`).join('');return rows?`<table class="table"><tr><th>Reminder</th><th>Scope</th><th>Time</th></tr>${rows}</table>`:'<p>No upcoming reminders.</p>'}

function renderAccounts(){
  const cards=appState.accountOrder.map(id=>{const a=appState.accountsData[id]; return `<div class="account-card" draggable="true" data-id="${id}"><div class="inline" style="justify-content:space-between"><strong>${esc(a.name)}</strong><span class="drag">⠿</span></div><p>${esc(a.sub||'')}</p><p class="small">Points ${a.points} · PC ${a.pcDone}/${a.targetPC} · Mobile ${a.mobDone}/${a.targetMobile}</p><div class="inline"><button class="btn" data-edit="${id}">Edit</button><button class="btn danger" data-del="${id}">Delete</button><button class="btn" data-rem="${id}">Reminder</button></div></div>`}).join('');
  document.getElementById('accountsView').innerHTML=`<div class="panel"><div class="inline" style="justify-content:space-between"><h3>Accounts</h3><button class="btn primary" id="newAccBtn">Add Account</button></div><div class="account-list" id="accountList">${cards}</div></div>`;
  document.getElementById('newAccBtn').onclick=()=>accountModal();
  document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>accountModal(b.dataset.edit));
  document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteAccount(b.dataset.del));
  document.querySelectorAll('[data-rem]').forEach(b=>b.onclick=()=>reminderModal(b.dataset.rem));
  bindDrag();
}
function accountModal(id){const acc=id?appState.accountsData[id]:{name:'',sub:'',targetPC:30,targetMobile:20}; openModal({title:id?'Edit Account':'Add Account',body:`<div class="form"><input name="name" value="${esc(acc.name)}" placeholder="Account name"/><input name="sub" value="${esc(acc.sub||'')}" placeholder="Subtitle"/><input type="number" name="targetPC" value="${acc.targetPC||30}"/><input type="number" name="targetMobile" value="${acc.targetMobile||20}"/></div>`,onSave:(o)=>{const name=o.querySelector('[name=name]').value.trim(); if(!name)return; if(id){Object.assign(appState.accountsData[id],{name,sub:o.querySelector('[name=sub]').value,targetPC:toNum(o.querySelector('[name=targetPC]').value,30),targetMobile:toNum(o.querySelector('[name=targetMobile]').value,20)}); pushActivity(`Account updated: ${name}`,id);} else {const nid=uid('acc'); appState.accountsData[nid]={id:nid,name,sub:o.querySelector('[name=sub]').value,queries:[],qindex:0,targetPC:toNum(o.querySelector('[name=targetPC]').value,30),targetMobile:toNum(o.querySelector('[name=targetMobile]').value,20),pcDone:0,mobDone:0,today:dayKey(),points:0,sessions:[],adjustments:[],alarm:'',reminders:[],loans:[],loanLog:[]}; appState.accountOrder.push(nid);appState.activeAccountId=nid; pushActivity(`Account created: ${name}`,nid);} saveLocal();o.remove();render();}})}
function deleteAccount(id){if(appState.accountOrder.length<=1){toast('At least one account is required');return}openModal({title:'Confirm delete',body:`<p>Delete <strong>${esc(appState.accountsData[id].name)}</strong>?</p>`,saveText:'Delete',onSave:(o)=>{delete appState.accountsData[id];appState.accountOrder=appState.accountOrder.filter(x=>x!==id);if(appState.activeAccountId===id)appState.activeAccountId=appState.accountOrder[0];pushActivity('Account deleted');saveLocal();o.remove();render();}})}
function reminderModal(id){openModal({title:'Add reminder',body:'<div class="form"><input name="text" placeholder="Reminder text"/><input type="datetime-local" name="due"/></div>',onSave:(o)=>{const t=o.querySelector('[name=text]').value;const due=o.querySelector('[name=due]').value;if(!t||!due)return;appState.accountsData[id].reminders.unshift({id:uid('rem'),text:t,due:new Date(due).toISOString(),done:false});pushActivity(`Reminder added to ${appState.accountsData[id].name}`);saveLocal();o.remove();render();}})}

function renderLoans(){const acc=getActiveAccount(); if(!acc)return; const filtered=filterLoans(acc.loans||[],loanFilter,loanSearch); const sum=loanSummary(acc.loans||[]); const rows=filtered.map(l=>`<tr><td>${esc(l.lender)}</td><td>${esc(l.borrower)}</td><td>${l.amount}</td><td>${fmtDate(l.date)}</td><td>${l.type}</td><td>${l.status}</td><td><button class="btn" data-paid="${l.id}">Paid</button> <button class="btn danger" data-rmloan="${l.id}">Delete</button></td></tr>`).join('');
  document.getElementById('loansView').innerHTML=`<div class="panel"><div class="inline" style="justify-content:space-between"><h3>Loan Manager</h3><button class="btn primary" id="newLoanBtn">Add Loan</button></div><div class="inline"><span class="pill ${loanFilter==='All'?'active':''}" data-f="All">All</span><span class="pill ${loanFilter==='Given'?'active':''}" data-f="Given">Given</span><span class="pill ${loanFilter==='Taken'?'active':''}" data-f="Taken">Taken</span><span class="pill ${loanFilter==='Active'?'active':''}" data-f="Active">Active</span><span class="pill ${loanFilter==='Paid'?'active':''}" data-f="Paid">Paid</span><input id="loanSearch" placeholder="Search lender/borrower" value="${esc(loanSearch)}"/></div><p>Balance indicator: Given ${sum.given} | Taken ${sum.taken} | Active ${sum.active}</p><table class="table"><tr><th>Lender</th><th>Borrower</th><th>Amount</th><th>Date</th><th>Type</th><th>Status</th><th>Actions</th></tr>${rows||'<tr><td colspan="7">No loans found.</td></tr>'}</table></div>
  <div class="panel"><h3>Loan History</h3><table class="table"><tr><th>Action</th><th>Loan</th><th>Amount</th><th>When</th></tr>${(acc.loanLog||[]).slice(0,20).map(i=>`<tr><td>${i.action}</td><td>${esc(i.lender)}→${esc(i.borrower)}</td><td>${i.amount}</td><td>${fmtDateTime(i.time)}</td></tr>`).join('')||'<tr><td colspan="4">No history</td></tr>'}</table></div>`;
  document.getElementById('newLoanBtn').onclick=()=>loanModal();
  document.querySelectorAll('[data-f]').forEach(x=>x.onclick=()=>{loanFilter=x.dataset.f;renderLoans()});
  document.getElementById('loanSearch').oninput=(e)=>{loanSearch=e.target.value;renderLoans()};
  document.querySelectorAll('[data-paid]').forEach(b=>b.onclick=()=>{markLoanPaid(acc,b.dataset.paid);pushActivity('Loan marked paid');saveLocal();renderLoans()});
  document.querySelectorAll('[data-rmloan]').forEach(b=>b.onclick=()=>{deleteLoan(acc,b.dataset.rmloan);pushActivity('Loan deleted');saveLocal();renderLoans()});
}
function loanModal(){const acc=getActiveAccount();openModal({title:'Add loan',body:`<div class="form"><input name="lender" placeholder="Who gave loan" value="${esc(acc.name)}"/><input name="borrower" placeholder="Who took loan"/><input type="number" name="amount" placeholder="Amount"/><input type="date" name="date"/><select name="direction"><option>Given</option><option>Taken</option></select><select name="status"><option>Active</option><option>Paid</option></select><textarea name="note" placeholder="Optional note"></textarea></div>`,onSave:(o)=>{addLoan(acc,{lender:o.querySelector('[name=lender]').value,borrower:o.querySelector('[name=borrower]').value,amount:o.querySelector('[name=amount]').value,date:o.querySelector('[name=date]').value,direction:o.querySelector('[name=direction]').value,status:o.querySelector('[name=status]').value,note:o.querySelector('[name=note]').value});pushActivity('Loan added');saveLocal();o.remove();renderLoans();}})}

function renderActivity(){document.getElementById('activityView').innerHTML=`<div class="panel"><h3>Activity Timeline</h3><table class="table"><tr><th>Event</th><th>Account</th><th>Time</th></tr>${appState.activityLog.slice(0,200).map(i=>`<tr><td>${esc(i.text)}</td><td>${esc(appState.accountsData[i.accountId]?.name||'—')}</td><td>${fmtDateTime(i.time)}</td></tr>`).join('')||'<tr><td colspan="3">No activity yet</td></tr>'}</table></div>`}

function renderSettings(){document.getElementById('settingsView').innerHTML=`<div class="panel"><h3>Settings</h3><div class="inline"><button class="btn" id="exportBtn">Export Backup</button><label class="btn">Import Backup<input id="importInput" type="file" accept="application/json" hidden></label><button class="btn" id="addGlobalReminderBtn">Add Global Reminder</button><button class="btn" id="resetBtn">Reset Local</button></div><p>Sync mode: ${appState.sync.mode}</p></div>`;document.getElementById('exportBtn').onclick=()=>downloadJson(`myrewards-backup-${Date.now()}.json`,{order:appState.accountOrder,data:appState.accountsData,globalReminders:appState.globalReminders,activityLog:appState.activityLog,settings:appState.settings});document.getElementById('importInput').onchange=async(e)=>{const f=e.target.files?.[0];if(!f)return;const j=await readFileJson(f);if(j.data&&j.order){appState.accountsData=j.data;appState.accountOrder=j.order;}if(j.globalReminders)appState.globalReminders=j.globalReminders;if(j.activityLog)appState.activityLog=j.activityLog;saveLocal();render();toast('Backup imported')};document.getElementById('addGlobalReminderBtn').onclick=()=>openModal({title:'Global reminder',body:'<div class="form"><input name="text" placeholder="Reminder"/><input type="datetime-local" name="due"/></div>',onSave:(o)=>{const t=o.querySelector('[name=text]').value;const due=o.querySelector('[name=due]').value;if(!t||!due)return;addGlobalReminder(t,new Date(due).toISOString());pushActivity('Global reminder added');o.remove();render();}});document.getElementById('resetBtn').onclick=()=>{localStorage.clear();location.reload()}}

function renderAccountDropdown(){const dd=document.getElementById('accountDropdown');dd.innerHTML=appState.accountOrder.map(id=>`<button data-sw="${id}" class="${id===appState.activeAccountId?'is-active':''}">${esc(appState.accountsData[id].name)}</button>`).join('')+'<hr><button id="quickAddAcc">+ Add Account</button>';dd.querySelectorAll('[data-sw]').forEach(b=>b.onclick=()=>{setActiveAccount(b.dataset.sw);pushActivity(`Switched account to ${appState.accountsData[b.dataset.sw].name}`,b.dataset.sw);saveLocal();dd.classList.add('hidden');render()});dd.querySelector('#quickAddAcc').onclick=()=>{dd.classList.add('hidden');currentRoute='accounts';renderRoute();accountModal()};document.getElementById('activeAccountName').textContent=getActiveAccount()?.name||'Select Account'}
function renderAlarmBadge(){const c=checkAlarms().length;const b=document.getElementById('alarmBadge');b.textContent=c;b.classList.toggle('hidden',!c)}

function bindDrag(){const list=document.getElementById('accountList');if(!list)return; let dragEl=null; list.querySelectorAll('.account-card').forEach(el=>{el.ondragstart=()=>{dragEl=el};el.ondragover=(e)=>e.preventDefault();el.ondrop=(e)=>{e.preventDefault();if(!dragEl||dragEl===el)return;const ids=[...list.children];const a=ids.indexOf(dragEl),b=ids.indexOf(el);if(a<b)el.after(dragEl);else el.before(dragEl);appState.accountOrder=[...list.querySelectorAll('.account-card')].map(x=>x.dataset.id);saveLocal();}})}

export function bindGlobalEvents(){document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{currentRoute=b.dataset.route;renderRoute()});document.getElementById('menuToggle').onclick=()=>document.getElementById('sidebar').classList.toggle('open');document.getElementById('profileSwitcherBtn').onclick=()=>document.getElementById('accountDropdown').classList.toggle('hidden');document.getElementById('openReminderPanel').onclick=()=>{currentRoute='dashboard';renderRoute();document.querySelector('#dashboardView .panel:last-child')?.scrollIntoView({behavior:'smooth'})};document.getElementById('themeToggle').onclick=()=>{appState.settings.darkMode=!appState.settings.darkMode;saveLocal();render()};window.onclick=(e)=>{if(!e.target.closest('.switcher-wrap'))document.getElementById('accountDropdown').classList.add('hidden')}}
